### ISSUE TITLE
Levantar infraestructura 

### ISSUE THREAD

**Issue by jreyesgar93** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-yefovar#3]

**Comment by jreyesgar93** [comment]
@Yalidt Apoyo a mafer en implementación de infraestructura

**Comment by yefovar** [comment]
Se ha levantado la infraestructura en varias sesiones debido a que se han acabado los creditos disponibles

**Comment by jreyesgar93** [comment]
cierro issue
