### ISSUE TITLE
Realizar las nuevas pruebas unitarias

### ISSUE THREAD

**Issue by jreyesgar93** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-yefovar#7]
Realizar las nuevas pruebas unitarias para nuevos cambios en el algoritmo y asegurar que cumplan con las anteriores.

**Comment by yefovar** [comment]
Se han realizado las pruebas unitarias con los cambios en los github actions del repositorio de Practica 1 Parte 2 considerando:

- [x] Verbose
- [x] Ajuste en parametros de la funcion
- [x] Ajuste de programacion para PLE

**Comment by jreyesgar93** [comment]
pruebas unitarias listas en repo anterior, agregaré pruebas para simplex C

**Comment by jreyesgar93** [comment]
cierro issue, se agregan pruebas unitarias de simplexC y corre bien
