### ISSUE TITLE
Cambio en Algoritmo

### ISSUE THREAD

**Issue by jreyesgar93** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-yefovar#8]
Cambio en el algoritmo para que resuelva también problemas de optimización de enteros. @jreyesgar93 Apoya a Yedam

**Comment by yefovar** [comment]
Se han realizado los cambios en la programacion considerando lo siguiente:
- [x] Verbose
- [x] Ajuste en parametros de la funcion
- [x] Ajuste de programacion para PLE

**Comment by jreyesgar93** [comment]
cierro issue
